services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    container_name: app
    build:
      dockerfile: Dockerfile.local
      context: ./
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3128:3128
    command: ["-verbose=true", "-port=3128"]
    